doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                # Dodaj tutaj inne ustawienia, takie jak dane uwierzytelniające, port, itp.
            warehouse:
                url: '%env(resolve:WAREHOUSE_DATABASE_URL)%'
                driver: 'pdo_mysql'
                # Dodaj tutaj inne ustawienia dla drugiego połączenia
        default_connection: default

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            warehouse:
                connection: warehouse
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Warehouse:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/EntityWarehouse'
                        prefix: 'App\EntityWarehouse'
                        alias: Warehouse

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system